name: Test GitHub Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: baruch.georgeponnumani@straive.com
        run: echo "Hello, world!"
